### ISSUE TITLE
Lights do not work

### ISSUE THREAD

**Issue by and-ampersand-and** [andrewdschmidt/PyBricks-Train-Motor-Control-Script#1]
When running with 88005 Powered Up led lights in one of the 2 ports, the code fails with an error:

```
The program was stopped (SystemAbort).
Init Timer 1
Init Timer 2
Traceback (most recent call last):
  File "motorcontrol.py", line 317, in <module>
  File "motorcontrol.py", line 264, in portcheck
AttributeError: 'device' object has no attribute 'stype'
```

This is due to the program assuming that any device is a motor.

**Comment by and-ampersand-and** [comment]
https://github.com/andrewdschmidt/PyBricks-Train-Motor-Control-Script/tree/Allow-Support-For-Lights
